# Generated by Django 4.2.11 on 2025-04-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_initial_tags'),
        ('projects', '0005_alter_projectimage_options_alter_projectimage_image'),
    ]

    operations = [
    ]
